name: Automatizar videos

on:
  push:
    paths:
      - 'videos/**'

jobs:
  procesar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3

      - name: Ejecutar prueba
        run: echo "Tu automatización está funcionando"
