name: Crear archivo prueba

on:
  push:
    paths:
      - 'videos/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Crear archivo
        run: |
          mkdir output
          echo "🔥 esto ya es automatización real 🔥" > output/resultado.txt

      - name: Subir resultado
        uses: actions/upload-artifact@v4
        with:
          name: resultado
          path: output/
