name: Procesar videos

on:
  push:
    paths:
      - 'videos/**'

jobs:
  procesar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Mostrar mensaje
        run: echo "Video detectado correctamente"
